version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:latest
    environment:
      JAVA_OPTS: "-Xmx256m -Xms32m "
    restart: always
    container_name: myapp
    ports:
      - "9014:9014"